### ISSUE TITLE
審査結果

### ISSUE THREAD

**Issue by InkoHX** [pmmpplugincontest2019/darumakka2-littleMaidMobPE#1]
# 審査結果

### コンフィグでカスタマイズできる。

スキンとかマントも着せれるのは良いと思います。
ただ、自分のスキンからBase64でエンコードされたスキンデータを取り出せたりするとコンフィグで設定するとき便利かもしれません。

### Configクラスの`default`の引数を利用していない
[ここ](https://github.com/pmmpplugincontest2019/darumakka2-littleMaidMobPE/blob/master/src/littleMaidMobPE/Maid.php#L245-#L284)のコードですが、Configクラスの`default`引数を利用すれば、この長い条件式はいりません。

```php
$this->config = new Config($this->getDataFolder() . "config.yml", Config::YAML, array());
```
ではなく
```php
$this->config = new Config($this->getDataFolder() . "config.yml", Config::YAML, [
    "SpawneggID" => 383
    // 続く
]);
```

条件式が消えて綺麗になります。

### 変数の名前を略す
正直これは良くないと思います。

```php
$pk = $event->getPacket();
$p = $event->getPlayer();
```

この変数ですが`Packet`を`pk`と略していたり`Player`を`p`と略すのは自分では分かりやすいかもしれませんが、読み手で`$p`, `$pk`が何を指しているのか分かりづらいです。
この場合変数の名前は`player`や`packet`にすると良いです。

### else や elseif を使いすぎている。
ネストは浅くしましょう。処理を関数化していくとネストをなくしていくことができると思います。
else elseif を使わないで！とはいいませんが、ネストを減らす工夫はしたほうがいいです。処理の仕組みが分かりづらいので

### それ以外にも

- クラスを活用してひとつのファイルに詰めないように設計を考えよう
- switch文や三項演算子をもっと活用しよう

**Comment by darumaka0625** [comment]
Thanks!
