### ISSUE TITLE
審査結果

### ISSUE THREAD

**Issue by hqmutaro** [pmmpplugincontest2019/darumakka2-littleMaidMobPE#3]
# はじめに
プラグイン作成お疲れ様です！
すごく良いプラグインだなと思いました(メイドさんかわいい...)

# 審査結果
## GOOD
- メイドさんかわいい
- 実装力

## BAD
- 大量の不必要なuse
できる限り必要なuseに絞りましょう...

- 連なるelseif
https://github.com/pmmpplugincontest2019/darumakka2-littleMaidMobPE/blob/5700022d42ca00b255424bcd4e5418d901267dd8/src/littleMaidMobPE/Maid.php#L772-L802

switchを使うとコンパクトに書けると感じました。

- 代入演算子が使われていない
評価には入れませんが代入演算子を使ったらさらにコンパクトに書けますというアレです。

https://github.com/pmmpplugincontest2019/darumakka2-littleMaidMobPE/blob/5700022d42ca00b255424bcd4e5418d901267dd8/src/littleMaidMobPE/Maid.php#L865
↓
```php
$x += 0;
```
[PHP: 代入演算子 - Manual](https://www.php.net/manual/ja/language.operators.assignment.php "PHP: 代入演算子 - Manual")

**Comment by darumakka0625** [comment]
Thanks!
