### ISSUE TITLE
審査結果

### ISSUE THREAD

**Issue by hmy2001** [pmmpplugincontest2019/darumakka2-littleMaidMobPE#4]
# 良くないと思ったところ
* 不要なクラスのインポート(use文)、またはまとめましょう
* コード同士が繋がっているので空行を入れましょう、空行があるだけでも読みやすくなります。
* 共通コードは一つのメソッドにしてそこを呼び出すようにしたほうがいいです
* 配列代入は複数コードに渡って代入するよりも、一気に代入したほうがいいです

```php
$maidData = ["eid" => int, "vector" => vector3]
```
と言った感じです

**Comment by darumakka0625** [comment]
Thanks!
