### ISSUE TITLE
審査結果

### ISSUE THREAD

**Issue by sei0511** [pmmpplugincontest2019/darumakka2-littleMaidMobPE#5]
# 良いと思った点👍
Configにて自由にスポーンさせるアイテムや、メイドさんのスキンを自由に変えられるというのがとてもいいと思います

メイドらしく主人に仕えるという感じで、敵に攻撃したり、そして雇用期間などもあり、しっかりとしているものだと思います
***

# 悪いと思った点👎
use文こんなに使うのかな...？
と思いました
不必要なuseは削除した方が良いと思います
***
https://github.com/pmmpplugincontest2019/darumakka2-littleMaidMobPE/blob/5700022d42ca00b255424bcd4e5418d901267dd8/src/littleMaidMobPE/Maid.php#L245-L284
非常にifのネストが深いです

``` php
class ExampleCode{

    private $default = 
    [
        "SpawneggID" => 383,
        "SpawneggDAMAGE" => 151,
        "Contract" => 354
        //以下略
    ];
    
    private function setDefaults(){
        
        $config = Config;

        foreach($default as $key => $set){
            $config->set($key, $set);
            $config->save();
        }
        
    }
}
```
このように他に関数を作ってあげると目にも優しくなるかもしれません(適当コードなので、エラー起こしたり、他に良い書き方もあるかもしれません
***
https://github.com/pmmpplugincontest2019/darumakka2-littleMaidMobPE/blob/5700022d42ca00b255424bcd4e5418d901267dd8/src/littleMaidMobPE/Maid.php#L906
個人的に変数名を略すのはぱっと見たときに何なのか分かりづらいので、略さず書くと良いと思いました
### 修正例
``` php
$packet = new MovePlayerPacket();
```
***
# まとめ
プラグインとしては申し分ないですが、コードに無駄な部分、削れる部分があったので、配列の書き方の工夫だったり、[三項演算子](https://www.javadrive.jp/php/if/index8.html)を使ってみるなどすると見やすく、さらに良いコードになるのではないかと感じました
短い期間でのAIの実装大変だったと思います
お疲れさまでした

**Comment by darumakka0625** [comment]
Thanks!
